name: denvak
description: "A new Flutter project."

publish_to: 'none' # Keep as is for private projects

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  desktop_window: ^0.4.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  http: ^1.2.2
  intl: ^0.19.0
  isolate: ^2.1.1
  syncfusion_localizations: ^27.1.48
  syncfusion_flutter_datagrid_export: ^27.1.48
  syncfusion_flutter_calendar: ^27.1.48
  syncfusion_flutter_datepicker: ^27.1.48
  syncfusion_flutter_charts: ^27.1.48
  syncfusion_flutter_gauges: ^27.1.48
  syncfusion_flutter_sliders: ^27.1.48
  syncfusion_flutter_pdf: ^27.1.48
  syncfusion_flutter_barcodes: ^27.1.48
  syncfusion_officechart: ^27.1.48
  syncfusion_flutter_maps: ^27.1.48
  syncfusion_flutter_signaturepad: ^27.1.48
  syncfusion_flutter_pdfviewer: ^27.1.48
  syncfusion_flutter_treemap: ^27.1.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment if you want to add images or other assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
